version: '3'

volumes:
  solrdata1:         # Store solr cores' data and configs
  logs:

services:
  solr-proxy:
    build: .
    image: solr-proxy
    ports: 
      - "8000:8000"
      - "9090:9090"
    environment:
      - SOLR_HOST=solr
      - SOLR_PORT=8983
      - LISTEN_PORT=8000
    volumes:
      - logs:/home/node/logs

  solr:
    image: solr
    volumes:
      - solrdata:/var/solr/




